### ISSUE TITLE
Fail on dateutil

### ISSUE THREAD

**Issue by Curtis2012** [leogomezz4t/PyTextNow_API#42]
I installed  PyTextNow to use in an app running on a Raspberry Pi 3A+, Python 3. I first took an error that the dateutil library was not found. I installed dateutil and now I get the following error. Suggestions to fix?

>>> %Run main.py
Traceback (most recent call last):
  File "/home/pi/clearskyalarm/main.py", line 10, in <module>
    import pytextnow as pytn
  File "/home/pi/.local/lib/python3.7/site-packages/pytextnow/__init__.py", line 2, in <module>
    from pytextnow.TNAPI import *
  File "/home/pi/.local/lib/python3.7/site-packages/pytextnow/TNAPI.py", line 8, in <module>
    from dateutil.relativedelta import relativedelta
  File "/home/pi/.local/lib/python3.7/site-packages/dateutil/relativedelta.py", line 118
    raise TypeError, "relativedelta only diffs datetime/date"
                   ^
SyntaxError: invalid syntax
>>>

**Comment by leogomezz4t** [comment]
Theres a good chance that your datetime is configured on your Raspberry Pi.
Is it a new RPi and if so try using raspiconfig to setup your timezone

**Comment by wunter8** [comment]
I think I ran into the same issue. `pip install python-dateutil` fixed it for me
