### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by anask1234** [leogomezz4t/PyTextNow_API#58]
Everytime i try to run this code 
```
import pytextnow as pytn
client = pytn.Client("jlaboy23", sid_cookie="s%3AIQTIp9fkmaNyFXgAnZTrhX0jS60TTTgG.MDUno6yJ9XRjnXc689g7NRk5YhlXyBYMQSQAX1%2F4DiQ", csrf_cookie="s%3AX_jgbWB_h6phng_eiTgL_cyd.e7zqr4zwkn5QMNZEI%2FWHF3XOHCEMAzyYYXu%2F4Nocc9A")

client.send_sms("Hi")
```
I get this error
```
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    client = pytn.Client("jlaboy23", sid_cookie="s%3AIQTIp9fkmaNyFXgAnZTrhX0jS60TTTgG.MDUno6yJ9XRjnXc689g7NRk5YhlXyBYMQSQAX1%2F4DiQ", csrf_cookie="s%3AX_jgbWB_h6phng_eiTgL_cyd.e7zqr4zwkn5QMNZEI%2FWHF3XOHCEMAzyYYXu%2F4Nocc9A")
  File "/home/runner/phone-info/venv/lib/python3.8/site-packages/pytextnow/TNAPI.py", line 36, in __init__
    with open(self._user_cookies_file, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/.cache/pip/pool/de/53/e4/user_cookies.json'
``` 
I dont understand why can someone help me.

**Comment by leogomezz4t** [comment]
For some reason, the user cookies file wasn't created or is in the wrong path. In the next update I'm going to remove the file entirely.

**Comment by anask1234** [comment]
> For some reason, the user cookies file wasn't created or is in the wrong path. In the next update I'm going to remove the file entirely.

ummm. not to be rude but whens the next time your gonna fix it?

**Comment by leogomezz4t** [comment]
The update is now live

**Comment by anask1234** [comment]
It still doesnt work :(
